### ISSUE TITLE
新更新后尝试搭建，无法进入后台

### ISSUE THREAD

**Issue by nakamiv** [hiliqi/xiaohuanxiong#23]
试着按照手册，用nginx，php7.2和7.3，redis全部部署完毕，运行文件夹public。前台一切正常。
尝试进入后台  http://xxx/admin
报错: 控制器不存在

删除网站文件夹和数据库，重新部署。还是报控制器不存在

换服务器，用了apache。其他配置同之前一样。尝试进入后台报错 
Not Found
The requested URL was not found on this server.

**Comment by hiliqi** [comment]
后台是二级域名，admin.xxx.com

**Comment by yipyeukyi** [comment]
当前日期正确的后台地址是 http://xxx/admin.php

**Comment by hiliqi** [comment]
就是这个地址
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiliqi/xiaohuanxiong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 凌晨3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiliqi/xiaohuanxiong] 新更新后尝试搭建，无法进入后台 (#23)





 
当前日期正确的后台地址是 http://xxx/admin.php
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nakamiv** [comment]
谢谢

**Comment by haiwunsiang** [comment]
Outlook邮件来的好及时，作者中心也是用同样的方法访问，http://xxx/author.php，看云有作者编写的文档，使用其中的伪静态，不修改配置二级域名可以直接访问。看云链接：https://www.kancloud.cn/hiliqi/raccoon5/1921259
